apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: mps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: mps project
  destinations:
    - namespace: '*'
      server: 'https://api.k8s.mps.plint.app'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
status: { }

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: mps
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: apps/mps/*
        repoURL: git@github.com:NUAB/argocd_applications.git
        revision: HEAD
        requeueAfterSeconds: 20
        template:
          metadata: { }
          spec:
            destination: { }
            project: ""
            source:
              repoURL: ""
  syncPolicy: { }
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: '{{ path.basename }}'
      name: 'mps-{{ path.basename }}'
    spec:
      destination:
        namespace: default
        server: 'https://api.k8s.mps.plint.app'
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      project: mps
      source:
        path: '{{ path }}'
        repoURL: git@github.com:NUAB/argocd_applications.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
status: { }
