apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
